const ActionType = {
    UPDATE_INPUTVALUE: 'UPDATE_INPUTVALUE',
    KEY_INPUTVALUE: 'KEY_INPUTVALUE',
    UPDATE_OPERATOR: 'UPDATE_OPERATOR',
    RESET_STATE: 'RESET_STATE',
    SUM_ADDHISTORY: 'SUM_ADDHISTORY',
    REMOVE_HISTORY: 'REMOVE_HISTORY'
}

module.exports = ActionType;